#############################################################################
# Makefile for building: LYCEEUI
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  LYCEEUI.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile LYCEEUI.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Idatabase -Imanagers -Imodels -Iui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LYCEEUI1.0.0
DISTDIR = /home/ubuntu-ecole/Bureau/LYCEEUI/.tmp/LYCEEUI1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		managers/adminManager.cpp \
		managers/passwordutils.cpp \
		managers/sessionmanager.cpp \
		models/cours.cpp \
		models/enseignant.cpp \
		models/etudiant.cpp \
		models/personne.cpp \
		models/session.cpp \
		models/ville.cpp \
		ui/formationpage.cpp \
		ui/formationwidget.cpp \
		ui/filedroplineedit.cpp \
		ui/loginpage.cpp \
		ui/passwordchangedialog.cpp \
		ui/adminpage.cpp \
		ui/enseignantpage.cpp \
		ui/etudiantspage.cpp \
		ui/mainwindow.cpp \
		ui/welcomescreen.cpp \
		database/dbConnexion.cpp \
		managers/scolariteManager.cpp \
		models/formation.cpp qrc_ressources.cpp \
		moc_formationpage.cpp \
		moc_formationwidget.cpp \
		moc_filedroplineedit.cpp \
		moc_loginpage.cpp \
		moc_passwordchangedialog.cpp \
		moc_adminpage.cpp \
		moc_enseignantpage.cpp \
		moc_etudiantspage.cpp \
		moc_mainwindow.cpp \
		moc_welcomescreen.cpp
OBJECTS       = main.o \
		adminManager.o \
		passwordutils.o \
		sessionmanager.o \
		cours.o \
		enseignant.o \
		etudiant.o \
		personne.o \
		session.o \
		ville.o \
		formationpage.o \
		formationwidget.o \
		filedroplineedit.o \
		loginpage.o \
		passwordchangedialog.o \
		adminpage.o \
		enseignantpage.o \
		etudiantspage.o \
		mainwindow.o \
		welcomescreen.o \
		dbConnexion.o \
		scolariteManager.o \
		formation.o \
		qrc_ressources.o \
		moc_formationpage.o \
		moc_formationwidget.o \
		moc_filedroplineedit.o \
		moc_loginpage.o \
		moc_passwordchangedialog.o \
		moc_adminpage.o \
		moc_enseignantpage.o \
		moc_etudiantspage.o \
		moc_mainwindow.o \
		moc_welcomescreen.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LYCEEUI.pro managers/adminManager.h \
		managers/passwordutils.h \
		managers/sessionmanager.h \
		models/cours.h \
		models/enseignant.h \
		models/etudiant.h \
		models/personne.h \
		models/session.h \
		models/ville.h \
		ui/formationpage.h \
		ui/formationwidget.h \
		ui/filedroplineedit.h \
		ui/loginpage.h \
		ui/passwordchangedialog.h \
		ui/adminpage.h \
		ui/enseignantpage.h \
		ui/etudiantspage.h \
		ui/mainwindow.h \
		ui/welcomescreen.h \
		database/dbConnexion.h \
		managers/scolariteManager.h \
		models/formation.h main.cpp \
		managers/adminManager.cpp \
		managers/passwordutils.cpp \
		managers/sessionmanager.cpp \
		models/cours.cpp \
		models/enseignant.cpp \
		models/etudiant.cpp \
		models/personne.cpp \
		models/session.cpp \
		models/ville.cpp \
		ui/formationpage.cpp \
		ui/formationwidget.cpp \
		ui/filedroplineedit.cpp \
		ui/loginpage.cpp \
		ui/passwordchangedialog.cpp \
		ui/adminpage.cpp \
		ui/enseignantpage.cpp \
		ui/etudiantspage.cpp \
		ui/mainwindow.cpp \
		ui/welcomescreen.cpp \
		database/dbConnexion.cpp \
		managers/scolariteManager.cpp \
		models/formation.cpp
QMAKE_TARGET  = LYCEEUI
DESTDIR       = 
TARGET        = LYCEEUI


first: all
####### Build rules

LYCEEUI:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LYCEEUI.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LYCEEUI.pro \
		ressources.qrc
	$(QMAKE) -o Makefile LYCEEUI.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
LYCEEUI.pro:
ressources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile LYCEEUI.pro

qmake_all: FORCE


all: Makefile LYCEEUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ressources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents managers/adminManager.h managers/passwordutils.h managers/sessionmanager.h models/cours.h models/enseignant.h models/etudiant.h models/personne.h models/session.h models/ville.h ui/formationpage.h ui/formationwidget.h ui/filedroplineedit.h ui/loginpage.h ui/passwordchangedialog.h ui/adminpage.h ui/enseignantpage.h ui/etudiantspage.h ui/mainwindow.h ui/welcomescreen.h database/dbConnexion.h managers/scolariteManager.h models/formation.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp managers/adminManager.cpp managers/passwordutils.cpp managers/sessionmanager.cpp models/cours.cpp models/enseignant.cpp models/etudiant.cpp models/personne.cpp models/session.cpp models/ville.cpp ui/formationpage.cpp ui/formationwidget.cpp ui/filedroplineedit.cpp ui/loginpage.cpp ui/passwordchangedialog.cpp ui/adminpage.cpp ui/enseignantpage.cpp ui/etudiantspage.cpp ui/mainwindow.cpp ui/welcomescreen.cpp database/dbConnexion.cpp managers/scolariteManager.cpp models/formation.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ressources.cpp
qrc_ressources.cpp: ressources.qrc \
		/usr/lib/qt5/bin/rcc \
		images/lycee.png
	/usr/lib/qt5/bin/rcc -name ressources ressources.qrc -o qrc_ressources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_formationpage.cpp moc_formationwidget.cpp moc_filedroplineedit.cpp moc_loginpage.cpp moc_passwordchangedialog.cpp moc_adminpage.cpp moc_enseignantpage.cpp moc_etudiantspage.cpp moc_mainwindow.cpp moc_welcomescreen.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_formationpage.cpp moc_formationwidget.cpp moc_filedroplineedit.cpp moc_loginpage.cpp moc_passwordchangedialog.cpp moc_adminpage.cpp moc_enseignantpage.cpp moc_etudiantspage.cpp moc_mainwindow.cpp moc_welcomescreen.cpp
moc_formationpage.cpp: ui/formationpage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/formationpage.h -o moc_formationpage.cpp

moc_formationwidget.cpp: ui/formationwidget.h \
		models/formation.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/formationwidget.h -o moc_formationwidget.cpp

moc_filedroplineedit.cpp: ui/filedroplineedit.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/filedroplineedit.h -o moc_filedroplineedit.cpp

moc_loginpage.cpp: ui/loginpage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/loginpage.h -o moc_loginpage.cpp

moc_passwordchangedialog.cpp: ui/passwordchangedialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/passwordchangedialog.h -o moc_passwordchangedialog.cpp

moc_adminpage.cpp: ui/adminpage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/adminpage.h -o moc_adminpage.cpp

moc_enseignantpage.cpp: ui/enseignantpage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/enseignantpage.h -o moc_enseignantpage.cpp

moc_etudiantspage.cpp: ui/etudiantspage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/etudiantspage.h -o moc_etudiantspage.cpp

moc_mainwindow.cpp: ui/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/mainwindow.h -o moc_mainwindow.cpp

moc_welcomescreen.cpp: ui/welcomescreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ubuntu-ecole/Bureau/LYCEEUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ubuntu-ecole/Bureau/LYCEEUI -I/home/ubuntu-ecole/Bureau/LYCEEUI/database -I/home/ubuntu-ecole/Bureau/LYCEEUI/managers -I/home/ubuntu-ecole/Bureau/LYCEEUI/models -I/home/ubuntu-ecole/Bureau/LYCEEUI/ui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/welcomescreen.h -o moc_welcomescreen.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ui/mainwindow.h \
		ui/welcomescreen.h \
		database/dbConnexion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

adminManager.o: managers/adminManager.cpp managers/adminManager.h \
		database/dbConnexion.h \
		managers/passwordutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminManager.o managers/adminManager.cpp

passwordutils.o: managers/passwordutils.cpp managers/passwordutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passwordutils.o managers/passwordutils.cpp

sessionmanager.o: managers/sessionmanager.cpp managers/sessionmanager.h \
		models/session.h \
		models/ville.h \
		models/enseignant.h \
		models/personne.h \
		models/etudiant.h \
		models/cours.h \
		database/dbConnexion.h \
		managers/passwordutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sessionmanager.o managers/sessionmanager.cpp

cours.o: models/cours.cpp models/cours.h \
		models/personne.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cours.o models/cours.cpp

enseignant.o: models/enseignant.cpp models/enseignant.h \
		models/personne.h \
		models/ville.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enseignant.o models/enseignant.cpp

etudiant.o: models/etudiant.cpp models/etudiant.h \
		models/personne.h \
		models/ville.h \
		models/cours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o etudiant.o models/etudiant.cpp

personne.o: models/personne.cpp models/personne.h \
		models/ville.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personne.o models/personne.cpp

session.o: models/session.cpp models/session.h \
		models/ville.h \
		models/enseignant.h \
		models/personne.h \
		models/etudiant.h \
		models/cours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o session.o models/session.cpp

ville.o: models/ville.cpp models/ville.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ville.o models/ville.cpp

formationpage.o: ui/formationpage.cpp ui/formationpage.h \
		managers/scolariteManager.h \
		models/formation.h \
		ui/formationwidget.h \
		ui/enseignantpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formationpage.o ui/formationpage.cpp

formationwidget.o: ui/formationwidget.cpp ui/formationwidget.h \
		models/formation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formationwidget.o ui/formationwidget.cpp

filedroplineedit.o: ui/filedroplineedit.cpp ui/filedroplineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedroplineedit.o ui/filedroplineedit.cpp

loginpage.o: ui/loginpage.cpp ui/loginpage.h \
		managers/sessionmanager.h \
		models/session.h \
		models/ville.h \
		models/enseignant.h \
		models/personne.h \
		models/etudiant.h \
		models/cours.h \
		ui/passwordchangedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginpage.o ui/loginpage.cpp

passwordchangedialog.o: ui/passwordchangedialog.cpp ui/passwordchangedialog.h \
		managers/passwordutils.h \
		managers/sessionmanager.h \
		models/session.h \
		models/ville.h \
		models/enseignant.h \
		models/personne.h \
		models/etudiant.h \
		models/cours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passwordchangedialog.o ui/passwordchangedialog.cpp

adminpage.o: ui/adminpage.cpp ui/adminpage.h \
		managers/adminManager.h \
		ui/filedroplineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminpage.o ui/adminpage.cpp

enseignantpage.o: ui/enseignantpage.cpp ui/enseignantpage.h \
		managers/scolariteManager.h \
		models/formation.h \
		models/enseignant.h \
		models/personne.h \
		models/session.h \
		models/ville.h \
		models/etudiant.h \
		models/cours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enseignantpage.o ui/enseignantpage.cpp

etudiantspage.o: ui/etudiantspage.cpp ui/etudiantspage.h \
		managers/scolariteManager.h \
		models/formation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o etudiantspage.o ui/etudiantspage.cpp

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

welcomescreen.o: ui/welcomescreen.cpp ui/welcomescreen.h \
		ui/formationpage.h \
		ui/loginpage.h \
		ui/adminpage.h \
		ui/etudiantspage.h \
		models/session.h \
		models/ville.h \
		models/enseignant.h \
		models/personne.h \
		models/etudiant.h \
		models/cours.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o welcomescreen.o ui/welcomescreen.cpp

dbConnexion.o: database/dbConnexion.cpp database/dbConnexion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbConnexion.o database/dbConnexion.cpp

scolariteManager.o: managers/scolariteManager.cpp managers/scolariteManager.h \
		models/formation.h \
		database/dbConnexion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scolariteManager.o managers/scolariteManager.cpp

formation.o: models/formation.cpp models/formation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formation.o models/formation.cpp

qrc_ressources.o: qrc_ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ressources.o qrc_ressources.cpp

moc_formationpage.o: moc_formationpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formationpage.o moc_formationpage.cpp

moc_formationwidget.o: moc_formationwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formationwidget.o moc_formationwidget.cpp

moc_filedroplineedit.o: moc_filedroplineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedroplineedit.o moc_filedroplineedit.cpp

moc_loginpage.o: moc_loginpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginpage.o moc_loginpage.cpp

moc_passwordchangedialog.o: moc_passwordchangedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passwordchangedialog.o moc_passwordchangedialog.cpp

moc_adminpage.o: moc_adminpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminpage.o moc_adminpage.cpp

moc_enseignantpage.o: moc_enseignantpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enseignantpage.o moc_enseignantpage.cpp

moc_etudiantspage.o: moc_etudiantspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_etudiantspage.o moc_etudiantspage.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_welcomescreen.o: moc_welcomescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_welcomescreen.o moc_welcomescreen.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

